[package]
name = "simple-rust-query-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
arrow = { version = "52.1.0", features = ["prettyprint"] }
async-stream = "0.3.5"
futures = "0.3.30"
snafu = "0.8.4"
tokio = { version = "1.39.1", features = ["full"] }
